package:
  name: memery
  version: 0.0.2
source:
  sha256: 16a027a9ef2ca9bc5890d7469412c5ec196ef052a1dbac4e93cc9f8a28c68068
  url: https://files.pythonhosted.org/packages/9c/12/1bee7cb2ff26f781e3abad05fb505bb37831699f64026157d6283a45c926/memery-0.0.2.tar.gz
about:
  dev_url: https://deepfates.github.io
  doc_url: https://deepfates.github.io
  home: https://deepfates.github.io
  license: Apache Software
  license_family: APACHE
  summary: search your image collections with natural language
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - deepfates
requirements:
  host:
  - pip
  - python
  - packaging
  run:
  - pip
  - python
  - packaging
test:
  imports:
  - memery
