package:
  name: memery
  version: 0.0.4
source:
  sha256: b271aa31173c18aaf550f034a532389aeaf039fa4645f7cf33dc751568bbf4ac
  url: https://files.pythonhosted.org/packages/92/97/0f43a1cee9793b7ee0e6fce16e687dfcb01066a38c9f6116e406474f582b/memery-0.0.4.tar.gz
about:
  dev_url: https://deepfates.github.io
  doc_url: https://deepfates.github.io
  home: https://deepfates.github.io
  license: Apache Software
  license_family: APACHE
  summary: search your image collections with natural language
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - deepfates
requirements:
  host:
  - pip
  - python
  - packaging
  - annoy==1.17.0
  - torchvision==0.8.2
  - tqdm==4.49.0
  - ipywidgets==7.5.1
  - torch==1.7.1
  - ipython==7.23.1
  - Pillow==8.2.0
  - typer==0.3.2
  - voila==0.2.10
  - clip-by-openai==0.1.1.5
  run:
  - pip
  - python
  - packaging
  - annoy==1.17.0
  - torchvision==0.8.2
  - tqdm==4.49.0
  - ipywidgets==7.5.1
  - torch==1.7.1
  - ipython==7.23.1
  - Pillow==8.2.0
  - typer==0.3.2
  - voila==0.2.10
  - clip-by-openai==0.1.1.5
test:
  imports:
  - memery
